# Generated by Django 4.1.3 on 2022-11-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('tensao', models.FloatField()),
            ],
        ),
    ]
